[package]
name = "adventofcode-2022"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode-2022"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

